### ISSUE TITLE
Ability to grab latest release from URL rather than specific build number

### ISSUE THREAD

**Issue by wesleynw** [PaperMC/papermc.io#164] opened 2022-02-23 02:34 UTC
Currently, if someone wants to grab the latest version of PaperMC from the website, they have to go on the website to find the most recent build. I propose there be a "latest" URL added, such that instead of the following url, which is the most recent build,

https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/212/downloads/paper-1.18.1-212.jar

There would also be: 
https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/212/downloads/LATEST/paper-1.18.1-212.jar

This would be extremely helpful for scripts, APIs, or AUR scripts to grab the latest release without having to update the build URL manually.

**Comment by Machine-Maker** [comment] 2022-02-23 02:35
Duplicate of https://github.com/PaperMC/bibliothek/issues/3

**Comment by electronicboy** [comment] 2022-02-23 02:36
this repo is for the static website, not the API

Also, "latest" is not an endpoint we desire to maintain, and querying the API is fairly trivial with tools like jq

**Closed by electronicboy** 2022-02-23 02:36 UTC
